export const SAVE_PERSONAL_DATA = 'SAVE_PERSONAL_DATA';
export const DELETE_PERSONAL_DATA = 'DELETE_PERSONAL_DATA';
export const SAVE_EDU_DATA = 'SAVE_EDU_DATA';
export const SAVE_EXP_DATA = 'SAVE_EXP_DATA';
export const DELETE_EXP_DATA = 'DELETE_EXP_DATA';
export const DELETE_EDU_DATA = 'DELETE_EDU_DATA';
export const SAVE_SKILL_DATA = 'SAVE_SKILL_DATA';
export const DELETE_SKILL_DATA = 'DELETE_SKILL_DATA';
